name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore MyWheel.sln

    - name: Build
      run: dotnet build MyWheel.sln --no-restore

    - name: Publish
      run: dotnet publish MyWheelApp.csproj -c Release -o release --nologo

    - name: Change base href
      run: sed -i 's/<base href="\/" \/>/<base href="\/MyWheel\/" \/>/g' release/wwwroot/index.html

    - name: Fix service worker paths
      run: |
        if [ -f "release/wwwroot/service-worker-assets.js" ]; then
          sed -i 's/"url": "\//"url": "\/MyWheel\//g' release/wwwroot/service-worker-assets.js
          sed -i 's/"url": "\([^"]*\)"/"url": "\/MyWheel\/\1"/g' release/wwwroot/service-worker-assets.js
          sed -i 's/\/MyWheel\/\/MyWheel\//\/MyWheel\//g' release/wwwroot/service-worker-assets.js
        fi

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Add 404.html for SPA routing
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: release/wwwroot

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
